import type { Page } from "@/lib/types";

const IMG = "https://raw.githubusercontent.com/Asabeneh/30-Days-Of-Python/master/images";

export const day04Page: Record<string, Page> = {
  "py30-day04": {
    slug: "py30-day04",
    title: "วันที่ 4 — สตริง (Strings)",
    lead: "เรียนรู้การสร้างและจัดการสตริงใน Python ทั้ง escape sequences, string formatting และ string methods",
    group: "สัปดาห์ที่ 1: พื้นฐาน Python",
    blocks: [
      { t: "h2", c: "สตริง (Strings)" },
      { t: "p", c: "ข้อความคือชนิดข้อมูล string ข้อมูลใด ๆ ที่เขียนเป็นข้อความถือเป็น string ข้อมูลที่อยู่ใน single quote, double quote หรือ triple quote ล้วนเป็น string มี string methods และ built-in functions หลายอย่างที่ใช้จัดการข้อมูล string ใช้ฟังก์ชัน len() เพื่อหาความยาวของสตริง" },

      { t: "h3", c: "การสร้างสตริง" },
      { t: "code", lang: "python", c: "letter = 'P'                # A string could be a single character or a bunch of texts\nprint(letter)               # P\nprint(len(letter))          # 1\ngreeting = 'Hello, World!'  # String could be made using a single or double quote,\"Hello, World!\"\nprint(greeting)             # Hello, World!\nprint(len(greeting))        # 13\nsentence = \"I hope you are enjoying 30 days of Python Challenge\"\nprint(sentence)" },
      { t: "p", c: "สตริงหลายบรรทัดสร้างได้ด้วย triple single quote (''') หรือ triple double quote (\"\"\")" },
      { t: "code", lang: "python", c: "multiline_string = '''I am a teacher and enjoy teaching.\nI didn't find anything as rewarding as empowering people.\nThat is why I created 30 days of python.'''\nprint(multiline_string)\n\n# Another way of doing the same thing\nmultiline_string = \"\"\"I am a teacher and enjoy teaching.\nI didn't find anything as rewarding as empowering people.\nThat is why I created 30 days of python.\"\"\"\nprint(multiline_string)" },

      { t: "h3", c: "การต่อสตริง (String Concatenation)" },
      { t: "p", c: "เราสามารถเชื่อมต่อสตริงเข้าด้วยกันได้ การเชื่อมต่อหรือรวมสตริงเรียกว่า concatenation" },
      { t: "code", lang: "python", c: "first_name = 'Asabeneh'\nlast_name  = 'Yetayeh'\nspace      = ' '\nfull_name  = first_name + space + last_name\nprint(full_name) # Asabeneh Yetayeh\n# Checking the length of a string using len() built-in function\nprint(len(first_name))  # 8\nprint(len(last_name))   # 7\nprint(len(first_name) > len(last_name)) # True\nprint(len(full_name)) # 16" },

      { t: "h3", c: "Escape Sequences ในสตริง" },
      { t: "p", c: "ใน Python และภาษาโปรแกรมอื่น \\ ตามด้วยตัวอักษรคือ escape sequence ที่ใช้บ่อยได้แก่:" },
      { t: "ul", c: [
        "\\n: ขึ้นบรรทัดใหม่",
        "\\t: Tab (8 ช่อง)",
        "\\\\: Backslash",
        "\\'': Single quote (')",
        "\\\"  : Double quote (\")",
      ]},
      { t: "code", lang: "python", c: "print('I hope everyone is enjoying the Python Challenge.\\nAre you ?') # line break\nprint('Days\\tTopics\\tExercises') # adding tab space or 4 spaces\nprint('Day 1\\t5\\t5')\nprint('Day 2\\t6\\t20')\nprint('Day 3\\t5\\t23')\nprint('Day 4\\t1\\t35')\nprint('This is a backslash  symbol (\\\\)') # To write a backslash\nprint('In every programming language it starts with \\\"Hello, World!\\\"\') # to write a double quote inside a single quote\n\n# output\n# I hope every one is enjoying the Python Challenge.\n# Are you ?\n# Days  Topics  Exercises\n# Day 1 5       5\n# Day 2 6       20\n# Day 3 5       23\n# Day 4 1       35\n# This is a backslash  symbol (\\)\n# In every programming language it starts with \"Hello, World!\"" },

      { t: "h3", c: "การจัดรูปแบบสตริง (String Formatting)" },

      { t: "h3", c: "รูปแบบเก่า: % Operator" },
      { t: "p", c: "ใน Python มีหลายวิธีในการจัดรูปแบบสตริง เครื่องหมาย % ใช้จัดรูปแบบตัวแปรให้แทรกลงในสตริง:" },
      { t: "ul", c: [
        "%s - String (หรือ object ใด ๆ ที่มี string representation เช่น ตัวเลข)",
        "%d - Integers",
        "%f - Floating point numbers",
        "%.Nf - Floating point numbers ที่มีทศนิยม N ตำแหน่ง",
      ]},
      { t: "code", lang: "python", c: "# Strings only\nfirst_name = 'Asabeneh'\nlast_name  = 'Yetayeh'\nlanguage   = 'Python'\nformated_string = 'I am %s %s. I teach %s' %(first_name, last_name, language)\nprint(formated_string)\n\n# Strings  and numbers\nradius = 10\npi     = 3.14\narea   = pi * radius ** 2\nformated_string = 'The area of circle with a radius %d is %.2f.' %(radius, area) # 2 refers the 2 significant digits after the point\n\npython_libraries = ['Django', 'Flask', 'NumPy', 'Matplotlib','Pandas']\nformated_string = 'The following are python libraries:%s' % (python_libraries)\nprint(formated_string) # \"The following are python libraries:['Django', 'Flask', 'NumPy', 'Matplotlib','Pandas']\"" },

      { t: "h3", c: "รูปแบบใหม่: str.format()" },
      { t: "p", c: "รูปแบบนี้ถูกนำมาใช้ใน Python เวอร์ชัน 3:" },
      { t: "code", lang: "python", c: "first_name = 'Asabeneh'\nlast_name  = 'Yetayeh'\nlanguage   = 'Python'\nformated_string = 'I am {} {}. I teach {}'.format(first_name, last_name, language)\nprint(formated_string)\na = 4\nb = 3\n\nprint('{} + {} = {}'.format(a, b, a + b))\nprint('{} - {} = {}'.format(a, b, a - b))\nprint('{} * {} = {}'.format(a, b, a * b))\nprint('{} / {} = {:.2f}'.format(a, b, a / b)) # limits it to two digits after decimal\nprint('{} % {} = {}'.format(a, b, a % b))\nprint('{} // {} = {}'.format(a, b, a // b))\nprint('{} ** {} = {}'.format(a, b, a ** b))\n\n# output\n# 4 + 3 = 7\n# 4 - 3 = 1\n# 4 * 3 = 12\n# 4 / 3 = 1.33\n# 4 % 3 = 1\n# 4 // 3 = 1\n# 4 ** 3 = 64\n\n# Strings  and numbers\nradius = 10\npi     = 3.14\narea   = pi * radius ** 2\nformated_string = 'The area of a circle with a radius {} is {:.2f}.'.format(radius, area) # 2 digits after decimal\nprint(formated_string)" },

      { t: "h3", c: "String Interpolation / f-Strings (Python 3.6+)" },
      { t: "p", c: "รูปแบบใหม่ล่าสุดคือ f-strings สตริงเริ่มต้นด้วย f และเราสามารถแทรกข้อมูลในตำแหน่งที่ต้องการได้:" },
      { t: "code", lang: "python", c: "a = 4\nb = 3\nprint(f'{a} + {b} = {a +b}')\nprint(f'{a} - {b} = {a - b}')\nprint(f'{a} * {b} = {a * b}')\nprint(f'{a} / {b} = {a / b:.2f}')\nprint(f'{a} % {b} = {a % b}')\nprint(f'{a} // {b} = {a // b}')\nprint(f'{a} ** {b} = {a ** b}')" },

      { t: "h3", c: "Python Strings เป็นลำดับของตัวอักษร" },
      { t: "p", c: "Python strings คือลำดับของตัวอักษร มีวิธีเข้าถึงค่าพื้นฐานเหมือนกับ sequence ที่มีลำดับอื่น ๆ เช่น lists และ tuples วิธีง่ายสุดในการดึงตัวอักษรแต่ละตัวคือการ unpack ลงในตัวแปรที่สอดคล้องกัน" },

      { t: "h3", c: "การ Unpack ตัวอักษร" },
      { t: "code", lang: "python", c: "language = 'Python'\na,b,c,d,e,f = language # unpacking sequence characters into variables\nprint(a) # P\nprint(b) # y\nprint(c) # t\nprint(d) # h\nprint(e) # o\nprint(f) # n" },

      { t: "h3", c: "การเข้าถึงตัวอักษรด้วย Index" },
      { t: "p", c: "ในการเขียนโปรแกรมนับเริ่มจากศูนย์ ดังนั้นตัวอักษรแรกของสตริงอยู่ที่ index 0 และตัวอักษรสุดท้ายอยู่ที่ length - 1" },
      { t: "image", src: `${IMG}/string_index.png`, alt: "String index", caption: "การนับ index ของสตริงใน Python" },
      { t: "code", lang: "python", c: "language     = 'Python'\nfirst_letter = language[0]\nprint(first_letter) # P\nsecond_letter = language[1]\nprint(second_letter) # y\nlast_index    = len(language) - 1\nlast_letter   = language[last_index]\nprint(last_letter) # n" },
      { t: "p", c: "ถ้าต้องการเริ่มนับจากขวา ใช้ negative indexing ได้เลย โดย -1 คือ index สุดท้าย:" },
      { t: "code", lang: "python", c: "language    = 'Python'\nlast_letter = language[-1]\nprint(last_letter) # n\nsecond_last = language[-2]\nprint(second_last) # o" },

      { t: "h3", c: "การตัดสตริง (Slicing)" },
      { t: "p", c: "ใน Python เราสามารถตัดสตริงออกเป็น substring ได้:" },
      { t: "code", lang: "python", c: "language    = 'Python'\nfirst_three = language[0:3] # starts at zero index and up to 3 but not include 3\nprint(first_three) #Pyt\nlast_three  = language[3:6]\nprint(last_three)  # hon\n# Another way\nlast_three = language[-3:]\nprint(last_three)  # hon\nlast_three = language[3:]\nprint(last_three)  # hon" },

      { t: "h3", c: "การกลับสตริง (Reversing)" },
      { t: "p", c: "ใน Python เราสามารถกลับสตริงได้ง่าย ๆ:" },
      { t: "code", lang: "python", c: "greeting = 'Hello, World!'\nprint(greeting[::-1]) # !dlroW ,olleH" },

      { t: "h3", c: "การข้ามตัวอักษรในการ Slicing" },
      { t: "p", c: "สามารถข้ามตัวอักษรขณะ slicing ได้โดยส่ง step argument:" },
      { t: "code", lang: "python", c: "language = 'Python'\npto = language[0:6:2] #\nprint(pto) # Pto" },

      { t: "h3", c: "String Methods" },
      { t: "p", c: "มี string methods จำนวนมากที่ช่วยจัดรูปแบบสตริง ดูตัวอย่างด้านล่าง:" },
      { t: "ul", c: [
        "capitalize(): แปลงตัวอักษรแรกเป็นตัวพิมพ์ใหญ่",
        "count(): นับจำนวนครั้งที่ substring ปรากฏในสตริง — count(substring, start=.., end=..)",
        "endswith(): เช็คว่าสตริงลงท้ายด้วยค่าที่ระบุหรือไม่",
        "expandtabs(): แทนที่ tab ด้วย spaces (default 8 ช่อง)",
        "find(): คืน index ของ substring ที่พบแรก ถ้าไม่พบคืน -1",
        "rfind(): คืน index ของ substring ที่พบท้ายสุด ถ้าไม่พบคืน -1",
        "format(): จัดรูปแบบสตริง",
        "index(): คืน index ต่ำสุดของ substring ถ้าไม่พบ raise ValueError",
        "rindex(): คืน index สูงสุดของ substring",
        "isalnum(): เช็คตัวอักษรและตัวเลข (alphanumeric)",
        "isalpha(): เช็คว่าตัวอักษรทั้งหมดเป็น alphabet (a-z, A-Z)",
        "isdecimal(): เช็คว่าตัวอักษรทั้งหมดเป็นทศนิยม (0-9)",
        "isdigit(): เช็คว่าตัวอักษรทั้งหมดเป็นตัวเลข (0-9 และ unicode บางตัว)",
        "isnumeric(): เช่น isdigit() แต่รับสัญลักษณ์ตัวเลขเพิ่มเติม เช่น ½",
        "isidentifier(): เช็คว่าเป็นชื่อตัวแปรที่ถูกต้อง",
        "islower(): เช็คว่าตัวอักษรทั้งหมดเป็นตัวพิมพ์เล็ก",
        "isupper(): เช็คว่าตัวอักษรทั้งหมดเป็นตัวพิมพ์ใหญ่",
        "join(): รวมสตริง",
        "strip(): ลบตัวอักษรที่ระบุออกจากต้นและท้ายสตริง",
        "replace(): แทนที่ substring ด้วยสตริงที่ระบุ",
        "split(): แยกสตริงโดยใช้ space หรือตัวคั่นที่ระบุ",
        "title(): คืนสตริงรูปแบบ title case",
        "swapcase(): แปลงตัวพิมพ์ใหญ่เป็นเล็กและเล็กเป็นใหญ่",
        "startswith(): เช็คว่าสตริงขึ้นต้นด้วยค่าที่ระบุหรือไม่",
      ]},
      { t: "code", lang: "python", c: "challenge = 'thirty days of python'\nprint(challenge.capitalize()) # 'Thirty days of python'" },
      { t: "code", lang: "python", c: "challenge = 'thirty days of python'\nprint(challenge.count('y')) # 3\nprint(challenge.count('y', 7, 14)) # 1, \nprint(challenge.count('th')) # 2" },
      { t: "code", lang: "python", c: "challenge = 'thirty days of python'\nprint(challenge.endswith('on'))   # True\nprint(challenge.endswith('tion')) # False" },
      { t: "code", lang: "python", c: "challenge = 'thirty\\tdays\\tof\\tpython'\nprint(challenge.expandtabs())   # 'thirty  days    of      python'\nprint(challenge.expandtabs(10)) # 'thirty    days      of        python'" },
      { t: "code", lang: "python", c: "challenge = 'thirty days of python'\nprint(challenge.find('y'))  # 5\nprint(challenge.find('th')) # 0" },
      { t: "code", lang: "python", c: "challenge = 'thirty days of python'\nprint(challenge.rfind('y'))  # 16\nprint(challenge.rfind('th')) # 17" },
      { t: "code", lang: "python", c: "first_name = 'Asabeneh'\nlast_name  = 'Yetayeh'\nage        = 250\njob        = 'teacher'\ncountry    = 'Finland'\nsentence = 'I am {} {}. I am a {}. I am {} years old. I live in {}.'.format(first_name, last_name, job, age, country)\nprint(sentence) # I am Asabeneh Yetayeh. I am 250 years old. I am a teacher. I live in Finland.\n\nradius = 10\npi     = 3.14\narea   = pi * radius ** 2\nresult = 'The area of a circle with radius {} is {}'.format(str(radius), str(area))\nprint(result) # The area of a circle with radius 10 is 314.0" },
      { t: "code", lang: "python", c: "challenge  = 'thirty days of python'\nsub_string = 'da'\nprint(challenge.index(sub_string))  # 7\nprint(challenge.index(sub_string, 9)) # error" },
      { t: "code", lang: "python", c: "challenge  = 'thirty days of python'\nsub_string = 'da'\nprint(challenge.rindex(sub_string))  # 7\nprint(challenge.rindex(sub_string, 9)) # error\nprint(challenge.rindex('on', 8)) # 19" },
      { t: "code", lang: "python", c: "challenge = 'ThirtyDaysPython'\nprint(challenge.isalnum()) # True\n\nchallenge = '30DaysPython'\nprint(challenge.isalnum()) # True\n\nchallenge = 'thirty days of python'\nprint(challenge.isalnum()) # False, space is not an alphanumeric character\n\nchallenge = 'thirty days of python 2019'\nprint(challenge.isalnum()) # False" },
      { t: "code", lang: "python", c: "challenge = 'thirty days of python'\nprint(challenge.isalpha()) # False, space is once again excluded\nchallenge = 'ThirtyDaysPython'\nprint(challenge.isalpha()) # True\nnum = '123'\nprint(num.isalpha())       # False" },
      { t: "code", lang: "python", c: "challenge = 'thirty days of python'\nprint(challenge.isdecimal())  # False\nchallenge = '123'\nprint(challenge.isdecimal())  # True\nchallenge = '\\u00B2'\nprint(challenge.isdigit())   # True \nchallenge = '12 3'\nprint(challenge.isdecimal())  # False, space not allowed" },
      { t: "code", lang: "python", c: "challenge = 'Thirty'\nprint(challenge.isdigit()) # False\nchallenge = '30'\nprint(challenge.isdigit())   # True\nchallenge = '\\u00B2'\nprint(challenge.isdigit())   # True" },
      { t: "code", lang: "python", c: "num = '10'\nprint(num.isnumeric()) # True\nnum = '\\u00BD' # ½\nprint(num.isnumeric()) # True\nnum = '10.5'\nprint(num.isnumeric()) # False" },
      { t: "code", lang: "python", c: "challenge = '30DaysOfPython'\nprint(challenge.isidentifier()) # False, because it starts with a number\nchallenge = 'thirty_days_of_python'\nprint(challenge.isidentifier()) # True" },
      { t: "code", lang: "python", c: "challenge = 'thirty days of python'\nprint(challenge.islower()) # True\nchallenge = 'Thirty days of python'\nprint(challenge.islower()) # False" },
      { t: "code", lang: "python", c: "challenge = 'thirty days of python'\nprint(challenge.isupper()) #  False\nchallenge = 'THIRTY DAYS OF PYTHON'\nprint(challenge.isupper()) # True" },
      { t: "code", lang: "python", c: "web_tech = ['HTML', 'CSS', 'JavaScript', 'React']\nresult = ' '.join(web_tech)\nprint(result) # 'HTML CSS JavaScript React'" },
      { t: "code", lang: "python", c: "web_tech = ['HTML', 'CSS', 'JavaScript', 'React']\nresult = '# '.join(web_tech)\nprint(result) # 'HTML# CSS# JavaScript# React'" },
      { t: "code", lang: "python", c: "challenge = 'thirty days of pythoonnn'\nprint(challenge.strip('noth')) # 'irty days of py'" },
      { t: "code", lang: "python", c: "challenge = 'thirty days of python'\nprint(challenge.replace('python', 'coding')) # 'thirty days of coding'" },
      { t: "code", lang: "python", c: "challenge = 'thirty days of python'\nprint(challenge.split()) # ['thirty', 'days', 'of', 'python']\nchallenge = 'thirty, days, of, python'\nprint(challenge.split(', ')) # ['thirty', 'days', 'of', 'python']" },
      { t: "code", lang: "python", c: "challenge = 'thirty days of python'\nprint(challenge.title()) # Thirty Days Of Python" },
      { t: "code", lang: "python", c: "challenge = 'thirty days of python'\nprint(challenge.swapcase())   # THIRTY DAYS OF PYTHON\nchallenge = 'Thirty Days Of Python'\nprint(challenge.swapcase())  # tHIRTY dAYS oF pYTHON" },
      { t: "code", lang: "python", c: "challenge = 'thirty days of python'\nprint(challenge.startswith('thirty')) # True\n\nchallenge = '30 days of python'\nprint(challenge.startswith('thirty')) # False" },

      { t: "h2", c: "💻 แบบฝึกหัด — วันที่ 4" },
      { t: "ol", c: [
        "ต่อสตริง 'Thirty', 'Days', 'Of', 'Python' ให้เป็น 'Thirty Days Of Python'",
        "ต่อสตริง 'Coding', 'For', 'All' ให้เป็น 'Coding For All'",
        "ประกาศตัวแปร company และกำหนดค่าเริ่มต้นเป็น \"Coding For All\"",
        "Print ตัวแปร company ด้วย print()",
        "Print ความยาวของ company string ด้วย len() และ print()",
        "เปลี่ยนตัวอักษรทั้งหมดเป็นพิมพ์ใหญ่ด้วย upper()",
        "เปลี่ยนตัวอักษรทั้งหมดเป็นพิมพ์เล็กด้วย lower()",
        "ใช้ capitalize(), title(), swapcase() เพื่อจัดรูปแบบ 'Coding For All'",
        "ตัด (slice) เอาคำแรกออกจากสตริง 'Coding For All'",
        "เช็คว่า 'Coding For All' มีคำว่า 'Coding' หรือไม่ โดยใช้ index, find หรือ methods อื่น",
        "แทนที่คำว่า 'coding' ในสตริง 'Coding For All' ด้วย 'Python'",
        "เปลี่ยน \"Python for Everyone\" เป็น \"Python for All\" ด้วย replace หรือ methods อื่น",
        "แยกสตริง 'Coding For All' ด้วย space เป็น separator (split())",
        "แยกสตริง \"Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon\" ด้วย comma",
        "ตัวอักษรที่ index 0 ของ 'Coding For All' คืออะไร",
        "index ท้ายสุดของ 'Coding For All' คือเท่าไร",
        "ตัวอักษรที่ index 10 ใน 'Coding For All' คืออะไร",
        "สร้าง acronym หรือตัวย่อสำหรับชื่อ 'Python For Everyone'",
        "สร้าง acronym หรือตัวย่อสำหรับ 'Coding For All'",
        "ใช้ index หาตำแหน่งการปรากฏแรกของ C ใน 'Coding For All'",
        "ใช้ index หาตำแหน่งการปรากฏแรกของ F ใน 'Coding For All'",
        "ใช้ rfind หาตำแหน่งการปรากฏท้ายสุดของ l ใน 'Coding For All People'",
        "ใช้ index หรือ find หาตำแหน่งการปรากฏแรกของคำว่า 'because' ในประโยค: 'You cannot end a sentence with because because because is a conjunction'",
        "ใช้ rindex หาตำแหน่งการปรากฏท้ายสุดของ 'because' ในประโยคข้างต้น",
        "ตัด phrase 'because because because' ออกจากประโยค: 'You cannot end a sentence with because because because is a conjunction'",
        "หาตำแหน่งการปรากฏแรกของคำว่า 'because' ในประโยคข้างต้น",
        "ตัด phrase 'because because because' ออกจากประโยคข้างต้น",
        "'Coding For All' ขึ้นต้นด้วย 'Coding' หรือไม่?",
        "'Coding For All' ลงท้ายด้วย 'coding' หรือไม่?",
        "'   Coding For All      ' — ลบ space ซ้ายและขวาออก",
        "ตัวแปรใดต่อไปนี้ได้ผล True เมื่อใช้ isidentifier(): 30DaysOfPython หรือ thirty_days_of_python",
        "List ต่อไปนี้มีชื่อ Python libraries: ['Django', 'Flask', 'Bottle', 'Pyramid', 'Falcon'] ต่อ list ด้วย hash กับ space",
        "ใช้ escape sequence ขึ้นบรรทัดใหม่แยกประโยคต่อไปนี้:\nI am enjoying this challenge.\nI just wonder what is next.",
        "ใช้ tab escape sequence เขียนบรรทัดต่อไปนี้:\nName      Age     Country   City\nAsabeneh  250     Finland   Helsinki",
        "ใช้ string formatting แสดงผลดังนี้:\nradius = 10\narea = 3.14 * radius ** 2\nThe area of a circle with radius 10 is 314 meters square.",
        "แสดงผลต่อไปนี้ด้วย string formatting:\n8 + 6 = 14\n8 - 6 = 2\n8 * 6 = 48\n8 / 6 = 1.33\n8 % 6 = 2\n8 // 6 = 1\n8 ** 6 = 262144",
      ]},
    ],
  },
};
