import type { Page } from "@/lib/types";

const IMG = "https://raw.githubusercontent.com/Asabeneh/30-Days-Of-Python/master/images";

export const day03Page: Record<string, Page> = {
  "py30-day03": {
    slug: "py30-day03",
    title: { th: "วันที่ 3 — ตัวดำเนินการ (Operators)", en: "" },
    lead: { th: "เรียนรู้ตัวดำเนินการของ Python ทั้งหมด: arithmetic, comparison, logical, assignment และ Boolean", en: "" },
    group: "สัปดาห์ที่ 1: พื้นฐาน Python",
    blocks: {
      th: [
        { t: "h2", c: "Boolean" },
        { t: "p", c: "ชนิดข้อมูล Boolean แทนค่าหนึ่งในสองค่า: True หรือ False การใช้งานชนิดข้อมูลนี้จะชัดเจนยิ่งขึ้นเมื่อเราเริ่มใช้ตัวดำเนินการเปรียบเทียบ ตัวอักษรแรกของ True ต้องเป็น T พิมพ์ใหญ่ และ False ต้องเป็น F พิมพ์ใหญ่ ต่างจาก JavaScript" },
        { t: "p", c: "ตัวอย่าง: Boolean Values" },
        { t: "code", lang: "python", c: "print(True)\nprint(False)" },

        { t: "h2", c: "ตัวดำเนินการ (Operators)" },
        { t: "p", c: "Python รองรับตัวดำเนินการหลายประเภท ในบทนี้จะโฟกัสที่ตัวดำเนินการหลักที่ใช้บ่อย" },

        { t: "h3", c: "ตัวดำเนินการกำหนดค่า (Assignment Operators)" },
        { t: "p", c: "ตัวดำเนินการกำหนดค่าใช้เพื่อกำหนดค่าให้กับตัวแปร เครื่องหมาย = ใน Python หมายถึงการ \"กำหนดค่า\" ไม่ใช่ \"เท่ากับ\" ทางคณิตศาสตร์" },
        { t: "image", src: `${IMG}/assignment_operators.png`, alt: "ตัวดำเนินการกำหนดค่า", caption: "ตัวดำเนินการกำหนดค่าทั้งหมดใน Python" },

        { t: "h3", c: "ตัวดำเนินการคณิตศาสตร์ (Arithmetic Operators)" },
        { t: "ul", c: [
          "การบวก (+): a + b",
          "การลบ (-): a - b",
          "การคูณ (*): a * b",
          "การหาร (/): a / b",
          "Modulus (%): a % b",
          "การหารทิ้งเศษ (//): a // b",
          "ยกกำลัง (**): a ** b",
        ]},
        { t: "image", src: `${IMG}/arithmetic_operators.png`, alt: "ตัวดำเนินการคณิตศาสตร์", caption: "ตัวดำเนินการคณิตศาสตร์ใน Python" },
        { t: "p", c: "ตัวอย่าง: Integers" },
        { t: "code", lang: "python", c: "# Arithmetic Operations in Python\n# Integers\n\nprint('Addition: ', 1 + 2)        # 3\nprint('Subtraction: ', 2 - 1)     # 1\nprint('Multiplication: ', 2 * 3)  # 6\nprint('Division: ', 4 / 2)        # 2.0  Division in Python gives floating number\nprint('Division: ', 6 / 2)        # 3.0         \nprint('Division: ', 7 / 2)        # 3.5\nprint('Division without the remainder: ', 7 // 2)   # 3,  gives without the floating number or without the remaining\nprint('Division without the remainder: ',7 // 3)    # 2\nprint('Modulus: ', 3 % 2)         # 1, Gives the remainder\nprint('Exponentiation: ', 2 ** 3) # 8 it means 2 * 2 * 2" },
        { t: "p", c: "ตัวอย่าง: Floats" },
        { t: "code", lang: "python", c: "# Floating numbers\nprint('Floating Point Number, PI', 3.14)\nprint('Floating Point Number, gravity', 9.81)" },
        { t: "p", c: "ตัวอย่าง: Complex numbers" },
        { t: "code", lang: "python", c: "# Complex numbers\nprint('Complex number: ', 1 + 1j)\nprint('Multiplying complex numbers: ',(1+1j) * (1-1j))" },
        { t: "p", c: "มาประกาศตัวแปรและกำหนดค่าตัวเลขกัน แนะนำให้ตั้งชื่อตัวแปรที่สื่อความหมาย (mnemonic variable name)" },
        { t: "p", c: "ตัวอย่าง:" },
        { t: "code", lang: "python", c: "# Declaring the variable at the top first\n\na = 3 # a is a variable name and 3 is an integer data type\nb = 2 # b is a variable name and 2 is an integer data type\n\n# Arithmetic operations and assigning the result to a variable\ntotal          = a + b\ndiff           = a - b\nproduct        = a * b\ndivision       = a / b\nremainder      = a % b\nfloor_division = a // b\nexponential    = a ** b\n\n# I should have used sum instead of total but sum is a built-in function - try to avoid overriding built-in functions\nprint(total) # if you do not label your print with some string, you never know where the result is coming from\nprint('a + b = ', total)\nprint('a - b = ', diff)\nprint('a * b = ', product)\nprint('a / b = ', division)\nprint('a % b = ', remainder)\nprint('a // b = ', floor_division)\nprint('a ** b = ', exponential)" },
        { t: "p", c: "ตัวอย่าง:" },
        { t: "code", lang: "python", c: "print('== Addition, Subtraction, Multiplication, Division, Modulus ==')\n\n# Declaring values and organizing them together\nnum_one = 3\nnum_two = 4\n\n# Arithmetic operations\ntotal     = num_one + num_two\ndiff      = num_two - num_one\nproduct   = num_one * num_two\ndiv       = num_two / num_one\nremainder = num_two % num_one\n\n# Printing values with label\nprint('total: ', total)\nprint('difference: ', diff)\nprint('product: ', product)\nprint('division: ', div)\nprint('remainder: ', remainder)" },
        { t: "p", c: "มาลองประยุกต์ใช้ความรู้ที่มีในการคำนวณ (พื้นที่, ปริมาตร, ความหนาแน่น, น้ำหนัก, เส้นรอบวง, ระยะทาง, แรง):" },
        { t: "code", lang: "python", c: "# Calculating area of a circle\nradius = 10                                 # radius of a circle\narea_of_circle = 3.14 * radius ** 2         # two * sign means exponent or power\nprint('Area of a circle:', area_of_circle)\n\n# Calculating area of a rectangle\nlength = 10\nwidth  = 20\narea_of_rectangle = length * width\nprint('Area of rectangle:', area_of_rectangle)\n\n# Calculating a weight of an object\nmass    = 75\ngravity = 9.81\nweight  = mass * gravity\nprint(weight, 'N')                          # Adding unit to the weight\n\n# Calculate the density of a liquid\nmass    = 75    # in Kg\nvolume  = 0.075 # in cubic meter\ndensity = mass / volume  # 1000 Kg/m^3\nprint(density, 'Kg/m^3') # Adding unit to the density" },

        { t: "h3", c: "ตัวดำเนินการเปรียบเทียบ (Comparison Operators)" },
        { t: "p", c: "ในการเขียนโปรแกรมเราเปรียบเทียบค่าต่าง ๆ ด้วยตัวดำเนินการเปรียบเทียบ ผลลัพธ์จะเป็น True หรือ False เสมอ" },
        { t: "image", src: `${IMG}/comparison_operators.png`, alt: "ตัวดำเนินการเปรียบเทียบ", caption: "ตัวดำเนินการเปรียบเทียบใน Python" },
        { t: "p", c: "ตัวอย่าง: Comparison Operators" },
        { t: "code", lang: "python", c: "print(3 > 2)     # True, because 3 is greater than 2\nprint(3 >= 2)    # True, because 3 is greater than 2\nprint(3 < 2)     # False,  because 3 is greater than 2\nprint(2 < 3)     # True, because 2 is less than 3\nprint(2 <= 3)    # True, because 2 is less than 3\nprint(3 == 2)    # False, because 3 is not equal to 2\nprint(3 != 2)    # True, because 3 is not equal to 2\nprint(len('mango') == len('avocado'))  # False\nprint(len('mango') != len('avocado'))  # True\nprint(len('mango') < len('avocado'))   # True\nprint(len('milk') != len('meat'))      # False\nprint(len('milk') == len('meat'))      # True\nprint(len('tomato') == len('potato'))  # True\nprint(len('python') > len('dragon'))   # False\n\n\n# Comparing something gives either a True or False\n\nprint('True == True: ', True == True)\nprint('True == False: ', True == False)\nprint('False == False:', False == False)" },
        { t: "p", c: "นอกจากตัวดำเนินการข้างต้นแล้ว Python ยังมีตัวดำเนินการพิเศษเพิ่มเติม:" },
        { t: "ul", c: [
          "is: คืนค่า True ถ้าตัวแปรทั้งสองอ้างถึง object เดียวกัน (x is y)",
          "is not: คืนค่า True ถ้าตัวแปรทั้งสองไม่ได้อ้างถึง object เดียวกัน (x is not y)",
          "in: คืนค่า True ถ้า list มีค่านั้นอยู่ (x in y)",
          "not in: คืนค่า True ถ้า list ไม่มีค่านั้น (x not in y)",
        ]},
        { t: "code", lang: "python", c: "print('1 is 1', 1 is 1)                   # True - because the data values are the same\nprint('1 is not 2', 1 is not 2)           # True - because 1 is not 2\nprint('A in Asabeneh', 'A' in 'Asabeneh') # True - A found in the string\nprint('B not in Asabeneh', 'B' in 'Asabeneh') # False - there is no uppercase B\nprint('coding' in 'coding for all') # True - because coding for all has the word coding\nprint('a in an:', 'a' in 'an')      # True\nprint('4 is 2 ** 2:', 4 is 2 ** 2)  # True" },

        { t: "h3", c: "ตัวดำเนินการเชิงตรรกะ (Logical Operators)" },
        { t: "p", c: "Python ใช้คำสงวน and, or และ not สำหรับตัวดำเนินการเชิงตรรกะ ต่างจากภาษาโปรแกรมอื่น ๆ ที่ใช้สัญลักษณ์ ตัวดำเนินการเชิงตรรกะใช้รวมคำสั่งเงื่อนไขหลายคำสั่งเข้าด้วยกัน" },
        { t: "image", src: `${IMG}/logical_operators.png`, alt: "ตัวดำเนินการเชิงตรรกะ", caption: "ตัวดำเนินการเชิงตรรกะใน Python" },
        { t: "code", lang: "python", c: "print(3 > 2 and 4 > 3) # True - because both statements are true\nprint(3 > 2 and 4 < 3) # False - because the second statement is false\nprint(3 < 2 and 4 < 3) # False - because both statements are false\nprint('True and True: ', True and True)\nprint(3 > 2 or 4 > 3)  # True - because both statements are true\nprint(3 > 2 or 4 < 3)  # True - because one of the statements is true\nprint(3 < 2 or 4 < 3)  # False - because both statements are false\nprint('True or False:', True or False)\nprint(not 3 > 2)     # False - because 3 > 2 is true, then not True gives False\nprint(not True)      # False - Negation, the not operator turns true to false\nprint(not False)     # True\nprint(not not True)  # True\nprint(not not False) # False" },

        { t: "h2", c: "💻 แบบฝึกหัด — วันที่ 3" },
        { t: "ol", c: [
          "ประกาศอายุของคุณเป็นตัวแปร integer",
          "ประกาศส่วนสูงของคุณเป็นตัวแปร float",
          "ประกาศตัวแปรที่เก็บ complex number",
          "เขียนโปรแกรมที่รับค่า base และ height ของสามเหลี่ยม แล้วคำนวณพื้นที่สามเหลี่ยม (area = 0.5 x b x h)\n    Enter base: 20\n    Enter height: 10\n    The area of the triangle is 100",
          "เขียนโปรแกรมที่รับค่าด้าน a, b, c ของสามเหลี่ยม แล้วคำนวณเส้นรอบรูป (perimeter = a + b + c)\nEnter side a: 5\nEnter side b: 4\nEnter side c: 3\nThe perimeter of the triangle is 12",
          "รับความยาวและความกว้างของสี่เหลี่ยมผืนผ้า แล้วคำนวณพื้นที่ (area = length x width) และเส้นรอบรูป (perimeter = 2 x (length + width))",
          "รับรัศมีของวงกลม แล้วคำนวณพื้นที่ (area = pi x r x r) และเส้นรอบวง (c = 2 x pi x r) โดย pi = 3.14",
          "คำนวณ slope, x-intercept และ y-intercept ของ y = 2x - 2",
          "Slope คือ (m = y2-y1/x2-x1) หา slope และ Euclidean distance ระหว่างจุด (2, 2) และ (6, 10)",
          "เปรียบเทียบ slope ในข้อ 8 และ 9",
          "คำนวณค่า y (y = x^2 + 6x + 9) ลองใช้ค่า x ต่าง ๆ และหาว่าเมื่อใด y จะเป็น 0",
          "หาความยาวของ 'python' และ 'dragon' แล้วสร้างคำสั่งเปรียบเทียบที่เป็น falsy",
          "ใช้ตัวดำเนินการ and เพื่อเช็คว่า 'on' อยู่ใน 'python' และ 'dragon' ทั้งคู่หรือไม่",
          "ประโยค: 'I hope this course is not full of jargon' ใช้ตัวดำเนินการ in เช็คว่า 'jargon' อยู่ในประโยคหรือไม่",
          "ไม่มี 'on' ใน 'dragon' และ 'python' ทั้งคู่",
          "หาความยาวของคำว่า 'python' แล้วแปลงค่าเป็น float จากนั้นแปลงเป็น string",
          "จำนวนคู่หารด้วย 2 ลงตัว เศษเป็นศูนย์ จะเช็คว่าตัวเลขเป็นเลขคู่หรือไม่ด้วย Python ได้อย่างไร?",
          "เช็คว่า floor division ของ 7 หาร 3 เท่ากับค่า int แปลงมาจาก 2.7 หรือไม่",
          "เช็คว่า type ของ '10' เท่ากับ type ของ 10 หรือไม่",
          "เช็คว่า int('9.8') เท่ากับ 10 หรือไม่",
          "เขียนโปรแกรมที่รับชั่วโมงทำงานและอัตราค่าจ้างต่อชั่วโมง แล้วคำนวณค่าจ้างรายสัปดาห์\nEnter hours: 40\nEnter rate per hour: 28\nYour weekly earning is 1120",
          "เขียนโปรแกรมที่รับจำนวนปี แล้วคำนวณจำนวนวินาทีที่มีชีวิตอยู่ โดยสมมติว่าอายุขัย 100 ปี\nEnter number of years you have lived: 100\nYou have lived for 3153600000 seconds.",
          "เขียนโปรแกรม Python แสดงตารางต่อไปนี้:\n1 1 1 1 1\n2 1 2 4 8\n3 1 3 9 27\n4 1 4 16 64\n5 1 5 25 125",
        ]},
      ],
      en: [],
    },
  },
};
